=== djenniex/brutis/tests/brutis.dtd
<?xml version="1.0" encoding="UTF-8" ?>
<!ELEMENT brutis (test)>
<!ELEMENT test (jobset+)>
<!ELEMENT jobset (libmemcache*, dataset+, operations+)>
<!ELEMENT libmemcache (option+)>
<!ELEMENT option (#PCDATA)>
<!ELEMENT dataset (key+, value*)>
<!ELEMENT key EMPTY>
<!ELEMENT value (#PCDATA)>
<!ELEMENT operations (operation+)>
<!ELEMENT operation EMPTY>

<!ATTLIST test
    name CDATA #REQUIRED
    desc CDATA #REQUIRED
    version CDATA #REQUIRED>

<!ATTLIST jobset
    name CDATA #REQUIRED
    forks CDATA "1" 
    operations CDATA #IMPLIED
    time CDATA #IMPLIED
    library (danga | libmemcache) "libmemcache">

<!ATTLIST option
    name CDATA #REQUIRED>

<!ATTLIST key
    name CDATA #REQUIRED
    start CDATA #REQUIRED
    end CDATA #REQUIRED
    pattern (sequential | random) "random"
    prefix CDATA "brutis-"
    divide CDATA "false">

<!ATTLIST value
    name CDATA #REQUIRED
    mode (generated | static) "generated"
    size CDATA #IMPLIED>

<!ATTLIST operation
    type (set | get | setMulti | getMulti | delete | append | replace | increment | decrement | sleep) "sleep"
    keyset CDATA #IMPLIED
    valueset CDATA #IMPLIED
    expire CDATA #IMPLIED
    count CDATA #IMPLIED>

=== djenniex/brutis/tests/append.xml
<?xml version="1.0"?>
<!DOCTYPE brutis SYSTEM "brutis.dtd">
<brutis>
    <test name='append' desc='Append test' version='1.0'>
        <jobset name='append_test' forks='16' time='300' library='libmemcache'>
            <libmemcache>
                <option name='Memcached::OPT_COMPRESSION'>FALSE</option>
            </libmemcache>
            <dataset>
                <key name='set' start='1' end='1000000' pattern='sequential' prefix='brutis-' divide='true'/>
                <key name='append' start='1' end='1000000' pattern='sequential' prefix='brutis-' divide='true'/>
                <key name='get' start='1' end='1000000' pattern='random' prefix='brutis-' divide='false'/>
                <value name='static' mode='static' size='18'>brutis static data</value>
            </dataset>
            <operations>
                <operation type='set' keyset='set' valueset='static'/>
                <operation type='append' keyset='append' valueset='static'/>
                <operation type='get' keyset='get'/>
            </operations>
        </jobset>
    </test>
</brutis>

=== djenniex/brutis/tests/keepalive.xml
<?xml version="1.0"?>
<!DOCTYPE brutis SYSTEM "brutis.dtd">
<brutis>
    <test name='Keepalive Test' desc='Do set every 5 minutes' version='1.0'>
        <jobset name='keepalive'>
            <dataset>
                <key name='set' start='1' end='1' prefix='brutiskeepalive-'/>
                <value name='generated' mode='generated' size='1'/>
            </dataset>
            <operations>
                <operation type='set' keyset='set' valueset='generated'/>
                <operation type='sleep' count='300'/>
            </operations>
        </jobset>
    </test>
</brutis>
