=== djenniex/brutis/tests/brutis.dtd
<?xml version="1.0" encoding="UTF-8" ?>
<!ELEMENT brutis (test)>
<!ELEMENT test (jobset+)>
<!ELEMENT jobset (libmemcache*, dataset+, operations+)>
<!ELEMENT libmemcache (option+)>
<!ELEMENT option (#PCDATA)>
<!ELEMENT dataset (key+, value*)>
<!ELEMENT key EMPTY>
<!ELEMENT value (#PCDATA)>
<!ELEMENT operations (operation+)>
<!ELEMENT operation EMPTY>

<!ATTLIST test
    name CDATA #REQUIRED
    desc CDATA #REQUIRED
    version CDATA #REQUIRED>

<!ATTLIST jobset
    name CDATA #REQUIRED
    forks CDATA "1" 
    operations CDATA #IMPLIED
    time CDATA #IMPLIED
    library (danga | libmemcache) "libmemcache">

<!ATTLIST option
    name CDATA #REQUIRED>

<!ATTLIST key
    name CDATA #REQUIRED
    start CDATA #REQUIRED
    end CDATA #REQUIRED
    pattern (sequential | random) "random"
    prefix CDATA "brutis-"
    divide CDATA "false">

<!ATTLIST value
    name CDATA #REQUIRED
    mode (generated | static) "generated"
    size CDATA #IMPLIED>

<!ATTLIST operation
    type (set | get | setMulti | getMulti | delete | append | replace | increment | decrement | sleep) "sleep"
    keyset CDATA #IMPLIED
    valueset CDATA #IMPLIED
    expire CDATA #IMPLIED
    count CDATA #IMPLIED>

=== djenniex/brutis/tests/danga_set.xml
<?xml version="1.0"?>
<!DOCTYPE brutis SYSTEM "brutis.dtd">
<brutis>
    <test name='Set' desc='Divided set test' version='1.0'>
        <jobset name='set' forks='2' time='300' library='danga'>
            <dataset>
                <key name='set' start='1' end='100000' pattern='sequential' prefix='brutis-' divide='true'/>
                <value name='generated' mode='generated' size='32'/>
            </dataset>
            <operations>
                <operation type='set' keyset='set' valueset='generated'/>
            </operations>
        </jobset>
    </test>
</brutis>

=== djenniex/brutis/tests/mixed.xml
<?xml version="1.0"?>
<!DOCTYPE brutis SYSTEM "brutis.dtd">
<brutis>
    <test name='Mixed' desc='Mixed operations test' version='1.0'>
        <jobset name='mix_operations_test' forks='4' time='1200'>
            <libmemcache>
                <option name='Memcached::OPT_COMPRESSION'>FALSE</option>
            </libmemcache>
            <dataset>
                <key name='set' start='1' end='1000' pattern='sequential' prefix='brutis-' divide='true'/>
                <key name='get' start='1' end='1000' pattern='sequential' prefix='brutis-' divide='true'/>
                <key name='setMulti' start='1' end='1000' pattern='sequential' prefix='brutis-' divide='true'/>
                <key name='getMulti' start='1' end='1000' pattern='random' prefix='brutis-' divide='true'/>
                <key name='append' start='1' end='1000' pattern='sequential' prefix='brutis-' divide='true'/>
                <key name='delete' start='1' end='1000' pattern='random' prefix='brutis-' divide='true'/>
                <key name='replace' start='1' end='1000' pattern='sequential' prefix='brutis-' divide='true'/>
                <key name='counter_set' start='1' end='10' pattern='sequential' prefix='brutiscounter-' divide='true'/>
                <key name='counter_inc' start='1' end='10' pattern='sequential' prefix='brutiscounter-' divide='true'/>
                <key name='counter_dec' start='1' end='10' pattern='sequential' prefix='brutiscounter-' divide='true'/>
                <value name='random' mode='generated' size='256'/>
                <value name='static' mode='static'>asdf1234</value>
                <value name='counter_static' mode='static' size='1'>0</value>
            </dataset>
            <operations>
                <operation type='set' keyset='set' valueset='static'/>
                <operation type='setMulti' keyset='setMulti' valueset='static' count='5'/>
                <operation type='append' keyset='append' valueset='random'/>
                <operation type='replace' keyset='replace' valueset='random'/>
                <operation type='get' keyset='get'/>
                <operation type='getMulti' keyset='getMulti' count='5'/>
                <operation type='delete' keyset='delete'/>
                <operation type='set' keyset='counter_set' valueset='counter_static'/>
                <operation type='increment' keyset='counter_inc'/>
                <operation type='decrement' keyset='counter_dec'/>
            </operations>
        </jobset>
    </test>
</brutis>

=== djenniex/brutis/tests/set_get.xml
<?xml version="1.0"?>
<!DOCTYPE brutis SYSTEM "brutis.dtd">
<brutis>
    <test name='Set_Get' desc='Set/Get test' version='1.0'>
        <jobset name='set_get'>
            <dataset>
                <key name='set' start='1' end='10000' pattern='sequential' prefix='brutis-' divide='false'/>
                <key name='get' start='1' end='10000' pattern='sequential' prefix='brutis-' divide='false'/>
                <value name='generated' mode='generated' size='256'/>
            </dataset>
            <operations>
                <operation type='set' keyset='set' valueset='generated'/>
                <operation type='get' keyset='get'/>
                <operation type='get' keyset='get'/>
                <operation type='get' keyset='get'/>
                <operation type='get' keyset='get'/>
                <operation type='get' keyset='get'/>
                <operation type='get' keyset='get'/>
                <operation type='get' keyset='get'/>
                <operation type='get' keyset='get'/>
                <operation type='get' keyset='get'/>
                <operation type='get' keyset='get'/>
            </operations>
        </jobset>
    </test>
</brutis>

=== djenniex/brutis/tests/replace.xml
<?xml version="1.0"?>
<!DOCTYPE brutis SYSTEM "brutis.dtd">
<brutis>
    <test name='Replace' desc='Replace test' version='1.0'>
        <jobset name='replace_test' time='1200'>
            <dataset>
                <key name='set' start='1' end='1000000' pattern='sequential' prefix='brutis-' divide='true'/>
                <key name='replace' start='1' end='1000000' pattern='sequential' prefix='brutis-' divide='true'/>
                <key name='get' start='1' end='1000000' pattern='random' prefix='brutis-' divide='false'/>
                <value name='static' mode='static' size='18'>brutis static data</value>
            </dataset>
            <operations>
                <operation type='set' keyset='set' valueset='static'/>
                <operation type='replace' keyset='replace' valueset='static'/>
                <operation type='get' keyset='get'/>
            </operations>
        </jobset>
    </test>
</brutis>

=== djenniex/brutis/tests/mixed_size_set.xml
<?xml version="1.0"?>
<!DOCTYPE brutis SYSTEM "brutis.dtd">
<brutis>
    <test name='Mixed set size' desc='Divided mixed size set test' version='1.0'>
        <jobset name='set_512' forks='2' time='60' library='danga'>
            <dataset>
                <key name='set' start='1' end='10000' pattern='sequential' prefix='brutis-' divide='true'/>
                <value name='d_512' mode='generated' size='512'/>
            </dataset>
            <operations>
                <operation type='set' keyset='set' valueset='d_512'/>
            </operations>
        </jobset>
        <jobset name='set_4096' forks='2' time='60'>
            <dataset>
                <key name='set' start='1' end='10000' pattern='sequential' prefix='brutis-' divide='true'/>
                <value name='d_4096' mode='generated' size='4096'/>
            </dataset>
            <operations>
                <operation type='set' keyset='set' valueset='d_4096'/>
            </operations>
        </jobset>
        <jobset name='set_16384' forks='2' time='60'>
            <dataset>
                <key name='set' start='1' end='10000' pattern='sequential' prefix='brutis-' divide='true'/>
                <value name='d_16384' mode='generated' size='16384'/>
            </dataset>
            <operations>
                <operation type='set' keyset='set' valueset='d_16384'/>
            </operations>
        </jobset>
        <jobset name='set_65536' forks='2' time='60'>
            <dataset>
                <key name='set' start='1' end='10000' pattern='sequential' prefix='brutis-' divide='true'/>
                <value name='d_65536' mode='generated' size='65536'/>
            </dataset>
            <operations>
                <operation type='set' keyset='set' valueset='d_65536'/>
            </operations>
        </jobset>
    </test>
</brutis>

=== djenniex/brutis/tests/set.xml
<?xml version="1.0"?>
<!DOCTYPE brutis SYSTEM "brutis.dtd">
<brutis>
    <test name='Set' desc='Divided set test' version='1.0'>
        <jobset name='set' forks='1'>
            <dataset>
                <key name='set' start='1' end='100' pattern='sequential' prefix='brutis-' divide='false'/>
                <value name='generated' mode='generated' size='32'/>
            </dataset>
            <operations>
                <operation type='set' keyset='set' valueset='generated'/>
            </operations>
        </jobset>
    </test>
</brutis>

=== djenniex/brutis/tests/set_multi.xml
<?xml version="1.0"?>
<!DOCTYPE brutis SYSTEM "brutis.dtd">
<brutis>
    <test name='Set' desc='multi set test' version='1.0'>
        <jobset name='set' forks='1' operations='100000' library='libmemcache'>
            <dataset>
                <key name='set' start='1' end='100000' pattern='sequential' prefix='brutis-' divide='true'/>
                <value name='generated' mode='generated' size='512'/>
            </dataset>
            <operations>
                <operation type='setMulti' keyset='set' valueset='generated' count='5'/>
            </operations>
        </jobset>
    </test>
</brutis>

=== djenniex/brutis/tests/delete.xml
<?xml version="1.0"?>
<!DOCTYPE brutis SYSTEM "brutis.dtd">
<brutis>
    <test name='Delete' desc='Delete test' version='1.0'>
        <jobset name='delete test' forks='4' operations='10000000'>
            <dataset>
                <key name='set' start='1' end='1000000' pattern='sequential' prefix='brutis-' divide='true'/>
                <key name='delete' start='1' end='1000000' pattern='sequential' prefix='brutis-' divide='true'/>
                <key name='get' start='1' end='1000000' pattern='sequential' prefix='brutis-' divide='true'/>
                <value name='static' mode='static' size='18'>brutis static data</value>
            </dataset>
            <operations>
                <operation type='set' keyset='set' valueset='static'/>
                <operation type='delete' keyset='delete'/>
                <operation type='get' keyset='get'/>
            </operations>
        </jobset>
    </test>
</brutis>
